config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("core/", include("core.urls")),
    path("projects/", include("projects.urls")),
    path("settings/", include("settings.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from .views import IndexView
from .views import DashboardView

app_name = 'core'
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
]

projects/urls.py
from django.urls import path

from . import views
from .views import AssignmentIndexView
from .views import AssignmentNewEditView
from .views import AssignmentDetailView
from .views import AssignmentAddCriteriaView
from .views import CriterionNewEditView
from .views import DescriptorNewEditView
from .views import SubmissionIndexView
from .views import SubmissionDetailView
from .views import SubmissionNewFilesView
from .views import SubmissionNewEditView

app_name = 'projects'
urlpatterns = [
    path("assignment/", AssignmentIndexView.as_view(), name="assignment-index"),
    path("assignment/subject_id=<int:subject_id>", AssignmentIndexView.as_view(), name="assignment-subject"),
    path("assignment/topic_id=<int:topic_id>", AssignmentIndexView.as_view(), name="assignment-topic"),
    path("assignment/new", AssignmentNewEditView.as_view(), name="assignment-new"),
    path("assignment/edit/<int:assignment_id>", AssignmentNewEditView.as_view(), name="assignment-edit"),
    path("assignment/detail/<int:assignment_id>", AssignmentDetailView.as_view(), name="assignment-detail"),
    path("assignment/add/<int:assignment_id>", AssignmentAddCriteriaView.as_view(), name="criteria-add"),
    path("criterion/new", CriterionNewEditView.as_view(), name="criterion-new"),
    path("criterion/edit/<int:criterion_id>", CriterionNewEditView.as_view(), name="criterion-edit"),
    path("descriptor/new", DescriptorNewEditView.as_view(), name="descriptor-new"),
    path("descriptor/edit/<int:descriptor_id>", DescriptorNewEditView.as_view(), name="descriptor-edit"),
    path("submission/", SubmissionIndexView.as_view(), name="submission-index"),
    path("submission/subject_id=<int:subject_id>", SubmissionIndexView.as_view(), name="submission-subject"),
    path("submission/topic_id=<int:topic_id>", SubmissionIndexView.as_view(), name="submission-topic"),
    path("submission/detail/<int:submission_id>", SubmissionDetailView.as_view(), name="submission-detail"),
    path("submission/file", SubmissionNewFilesView.as_view(), name="submission-file"),
    path("submission/new", SubmissionNewEditView.as_view(), name="submission-new"),
    path("submission/edit/<int:submission_id>", SubmissionNewEditView.as_view(), name="submission-edit"),
]

settings/urls.py
from django.urls import path

from .views import IndexView
from .views import SubjectView
from .views import TopicView
from .views import SetView

app_name = 'settings'
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("subject/new", SubjectView.as_view(), name="new-subject"),
    path("subject/<int:subject_id>", SubjectView.as_view(), name="subject"),
    path("topic/new", TopicView.as_view(), name="new-topic"),
    path("topic/<int:topic_id>", TopicView.as_view(), name="topic"),
    path("set/new", SetView.as_view(), name="new-set"),
    path("set/<int:set_id>", SetView.as_view(), name="set"),
]

assignment/models.py
from django.db import models
from django.contrib.auth.models import User

from settings.models import Subject
from settings.models import Topic
from settings.models import Member


class Assignment(models.Model):
    PUBLIC = 'Public'
    
    STATE_TYPE = {
        PUBLIC: 'Public',
    }
    
    ##Fileds    
    #NOTE: Change teacher to author!
    name = models.CharField(max_length=255, null=False)
    state = models.CharField(choices=STATE_TYPE, default=PUBLIC)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Member, on_delete=models.CASCADE)
    note = models.CharField(max_length=255, null=True)
    update_time = models.DateTimeField(auto_now=True)
    
    ##Metadata
    
    ##Methods    
    def __str__(self):
        return self.name

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from core.models import File
from settings.models import Subject
from settings.models import Topic
from settings.models import Member


class Descriptor(models.Model):
    """Descriptors for criteria."""
    
    class Types(models.TextChoices):
        GENERAL = 'TYPE_GENERAL', _('General')
        SPECIAL = 'TYPE_SPECIAL', _('Specialised')

    ## Fileds    
    name = models.CharField(max_length=255, null=False)
    description = models.CharField(max_length=255, null=True)
    type = models.JSONField(choices=Types.choices, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)
    
    ## Metadata
    
    ## Methods   
    def filter_last(user, limit):
        return Descriptor.objects.filter(author__id=user.id).order_by('-update_time')[:limit]

    def __str__(self):
        return self.name


class Criterion(models.Model):
    """Avaluation criteria."""
    
    class Groups(models.TextChoices):
        GENERAL = 'GROUP_GENERAL', _('General')
        SPECIAL = 'GROUP_SPECIAL', _('Specialised')

    class Weights(models.IntegerChoices):
        LOW = 1, _('Low')
        MIDDLE = 2, _('Middle')
        HIGH = 3, _('High')

    ## Fileds    
    name = models.CharField(max_length=255, null=False)
    note = models.CharField(max_length=255, null=True)
    group = models.JSONField(choices=Groups.choices, null=False)
    weight = models.IntegerField(choices=Weights.choices, default=Weights.LOW, null=False)
    descriptors = models.ManyToManyField(Descriptor, default=Groups.GENERAL)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)
    
    ## Metadata
    
    ## Methods    
    def filter_by_author(user, limit=None):
        try:
            return Criterion.objects.filter(author__id=user.id).order_by('-update_time')[:limit]
        except:
            return None

    def __str__(self):
        return self.name


class Assignment(models.Model):
    """Assignments for students."""
    
    class States(models.TextChoices):
        PUBLIC = 'STATE_PUBLIC', _('Public')
        DRAFT = 'STATE_DRAFT', _('Draft')
        ARCHIVED = 'STATE_ARCHIVED', _('Archived')

    ## Fileds    
    name = models.CharField(max_length=255, null=False)
    state = models.JSONField(choices=States.choices)
    criteria = models.ManyToManyField(Criterion)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    note = models.CharField(max_length=255, null=True)
    update_time = models.DateTimeField(auto_now=True)
    
    ## Metadata
    
    ## Methods    
    def filter_by_author(user, limit=None):
        try:
            return Assignment.objects.filter(author__id=user.id).order_by('-update_time')[:limit]
        except:
            return None

    def filter_by_subject(user, id):
        try:
            return Assignment.objects.filter(subject=id, author=user.id).order_by('-update_time')
        except:
            return None

    def filter_by_topic(user, id):
        try:
            return Assignment.objects.filter(topic=id, author=user.id).order_by('-update_time')
        except:
            return None

    def __str__(self):
        return self.name


class Submission(models.Model):
    """Submission from students."""
    
    class States(models.TextChoices):
        DRAFT = 'STATE_DRAFT', _('Draft: working on it')
        REVIEW = 'STATE_REVIEW', _('Review: changes needed')
        FINISHED = 'STATE_FINISHED', _('Finished: done')
        ARCHIVED = 'STATE_ARCHIVED', _('Archived: stored for me')

    ## Fileds    
    name = models.CharField(max_length=255, null=False)
    note = models.CharField(max_length=255, null=True)
    text = models.TextField(max_length=4000, null=True)
    file = models.ManyToManyField(File, null=True)
    state = models.JSONField(choices=States.choices)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_created=True)
    update_time = models.DateTimeField(auto_now=True)
    
    ## Metadata
    
    ## Methods    
    def filter_by_author(self, user, limit):
        try:
            return self.objects.filter(author__id=user.id).order_by('-update_time')[:limit]
        except self.DoesNotExist:
            return None

    def filter_by_subject(self, user, subject, limit):
        try:
            return self.objects.filter(author__id=user.id, assignment__subject=subject).order_by('-update_time')[:limit]
        except self.DoesNotExist:
            return None

    def filter_by_state(self, user, state):
        try:
            return self.objects.filter(state=state, author__id=user.id).order_by('-update_time')
        except self.DoesNotExist:
            return None

    def __str__(self):
        return f"{self.name}({self.author})"

settings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Member(models.Model):

    class Roles(models.TextChoices):
        STUDENT = 'ROLE_STUDENT', _('Student')
        INSTRUCTOR = 'ROLE_INSTRUCTOR', _('Instructor')
        TEACHER = 'ROLE_TEACHER', _('Teacher')
        ADMIN = 'ROLE_ADMIN', _('Admin')
    
    ##Fileds
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.JSONField(choices=Roles.choices, help_text='Select an appropriate role.')
    
    ##Metadata
    
    ##Methods
    def __str__(self):
        return self.user.username


class Subject(models.Model):
    ##Fileds
    name = models.CharField(max_length=100)
    lead = models.ManyToManyField(User)
    #pub_date = models.DateTimeField("date published")

    ##Metadata    
    
    ##Methods
    def get_subjects_by_owner(user):
        return Subject.objects.filter(lead=user.id).order_by('name')

    def __str__(self):
        return self.name


class Topic(models.Model):
    heading = models.CharField(max_length=200)
    text = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    ##Metadata
    
    ##Methods
    def get_topics_by_owner(user):
        return Topic.objects.filter(author=user.id).order_by('heading')

    def __str__(self):
        return self.heading


class Set(models.Model):
    class Types(models.TextChoices):
        YEAR = 'TYPE_YEAR', _('Year Group')
        TUTOR = 'TYPE_TUTOR', _('Tutor Group')
        PERFORM = 'TYPE_PERFORM', _('Performance')
        INTEREST = 'TYPE_INTEREST', _('Interest')

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100, choices=Types)
    lead = models.ManyToManyField(User)
    
    ##Metadata

    ##Methods
    def __str__(self):
        return self.name

assignment/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.template import loader

from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView

from .models import Member
from .models import Assignment
from .models import Subject

from .forms import AssignmentForm


class IndexView(PermissionRequiredMixin, TemplateView):
    """Conbined view of all assignments."""

    permission_required = ('assignment.view_assignment', 'settings.view_member', 'settings.view_subject')
    template_name = "index.html"
    
    def get_current_user(self):
        return Member.objects.get(pk=self.request.user.id)
        
    def get_queryset(self):
        return Assignment.objects.filter(teacher__id=self.request.user.id).order_by('-update_time')[:8]
    
    def get(self, request, subject_id=None):
        print(self.get_permission_required())   
        print(request.user.has_perm('assignment.edit_assignment'))   

        ## Top section
        try:
            assignments = self.get_queryset()
        except Assignment.DoesNotExist:
            assignments = None
        
        ## Assignments by subject section
        # List of subjects for buttons
        subjects = Subject.objects.all().order_by('name')
        
        # Select assignments
        try:
            selected_subject = Subject.objects.get(pk = subject_id)
            assignments_by_subject = Assignment.objects.filter(subject=subject_id, teacher=self.get_current_user()).order_by('-update_time')
        except Subject.DoesNotExist:
            selected_subject = None
            assignments_by_subject = self.get_queryset()

        # Render all data
        context = {'assignments':assignments, 'subjects':subjects, 'selected_subject':selected_subject, 'assignments_by_subject':assignments_by_subject}
        return render(request, 'assignment/index.html', context)


class NewEditView(PermissionRequiredMixin, UpdateView):
    """Creat new or edit existing assignment."""

    model = Assignment
    form_class = AssignmentForm
    permission_required = ('assignment.add_assignment', 'assignment.change_assignment', 'settings.view_member')
    template_name = "assignment/new-edit.html"

    def get_current_user(self):
        return Member.objects.get(pk=self.request.user.id)
    
    def get(self, request, assignment_id=None):
        # Test GET parameters to edit or inser data
        try:
            assignment = self.model.objects.get(pk=assignment_id)
            
            ini_values = {
                'name' : assignment.name, 
                'state' : assignment.state, 
                'subject' : assignment.subject, 
                'topic' : assignment.topic, 
                'teacher' : assignment.teacher, 
                'note' : assignment.note,
             }
            
            form = self.form_class(request=request, initial=ini_values)
        except self.model.DoesNotExist:
            # Send reqest.user to the form
            assignment = None
            form = self.form_class(request=request)

        context = {'assignment' : assignment, 'form' : form}
        return render(request, self.template_name, context)

    def post(self, request, assignment_id=None):
        form = self.form_class(request.POST, request=request)
        try:
            # Prepare data to save
            assignment = self.model.objects.get(pk=assignment_id)
            
            if form.is_valid():
                assignment.name = form.cleaned_data['name']
                assignment.state = form.cleaned_data['state']
                assignment.subject = form.cleaned_data['subject']
                assignment.topic = form.cleaned_data['topic']
                assignment.author = self.get_current_user() # Select box or automatic??
                assignment.note = form.cleaned_data['note']
                assignment.save()
            return HttpResponseRedirect(reverse("assignment:detail", kwargs={'assignment_id':assignment_id}))
        except self.model.DoesNotExist:
            # New data to save
            if form.is_valid():
                assignment = form.save(commit=False)
                assignment.teacher = self.get_current_user()
                assignment.save()
                form.save_m2m()            
            return HttpResponseRedirect('{}#top'.format(reverse("assignment:index")))
    
    
class DetailView(PermissionRequiredMixin, TemplateView):
    """Show details of selected assignemnt with a link to edit."""
    
    model = Assignment
    permission_required = ('assignment.view_assignment')
    template_name = "detail.html"

    def get(self, request, assignment_id):
        assignment = self.model.objects.get(pk=assignment_id)

        context = {'assignment':assignment}
        return render(request, 'assignment/detail.html', context)
    

projects/templates/assignment/criterion-new-edit.html
{# New Assignment template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Create or edit criterion{% endblock %}

{% block content %}
    <section id="top" class="form">
        <div class="wide-envelop">
        {% if criterion %}
            <h1>{{ criterion.name }}</h1>
            <p>criterion by {{criterion.author}}</p>
            {{ session_context.last_assignment_url}}
            <form action="{% url 'projects:criterion-edit' criterion.id %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% else %}
            <h1>New Criterion</h1>

            <form action="{% url 'projects:criterion-new' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <span class="button"><a href="{% url 'projects:descriptor-new' %}" title="Add your new criterion.">Add</a></span>
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% endif %}
        </div>
    </section>

    {#TODO: Save as a copy#}
    <section id="navigation">
        <span class="button"><a href="{{ wizard }}#criteria" title="Settings">&lt;</a></span>
        <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="button-logout">Log Out</button>
        </form>    
    </section>
{% endblock %}

projects/templates/assignment/index.html
{# Assignment template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Assignments{% endblock %}

{% block content %}
    <section id="top" class="main">
        <h1>Assignments</h1>
        <div class="wide-white-block">
        {%if assignments %}
            {% for assignment in assignments %}
                <span class="block-envelop">
                    {% if assignment.subject %} 
                        <span class="group">
                            {{ assignment.subject.name }}
                        </span>
                        <span class="data">
                            <a href="{% url 'projects:assignment-detail' assignment.id %}">{{ assignment.name }}</a>
                        </span>
                    {% else %}
                        No Subject
                    {% endif %}
                </span>
            {% endfor %}    
        {% else %}    
            <p class='info'>No assignment found.</p>
        {% endif %}    
        </div>    
    </section>

    <section id="subject" class="darkblue">
        <h2>Assignments {% if selected_subject %} for {{ selected_subject.name }} {% else %} by subject {% endif %}</h2>
        <div class="button-list">
        {% if perms.settings.add_subject %}
            <span class="button"><a href="{% url 'settings:new-subject' %}" title="Add your new subject.">+</a></span>
        {% endif %}
        <span class="button"><a href="{% url 'projects:assignment-index' %}#subject">All</a></span>
        {% for subject in subjects %}
            <span class="button"><a href="{% url 'projects:assignment-subject' subject.id %}#subject">{{ subject.name }}</a></span>
        {% endfor %}
        </div>
        
        <div class="wide-envelop">
            <div class="wide-darkblue-block">
            {%if assignments_by_subject and selected_subject %}
                {% for assignment in assignments_by_subject %}
                    <span class="block-envelop">
                        {% if assignment.subject %} 
                            <span class="group">
                                {{ assignment.subject.name }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:assignment-detail' assignment.id %}">{{ assignment.name }}</a>
                            </span>
                        {% else %}
                            No assignment
                        {% endif %}
                    </span>
                {% endfor %}    
            {%elif assignments_by_subject and not selected_subject %}
                {% for assignment in assignments_by_subject %}
                    <span class="block-envelop">
                        {% if assignment.subject %} 
                            <span class="group">
                                {{ assignment.subject.name }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:assignment-detail' assignment.id %}">{{ assignment.name }}</a>
                            </span>
                        {% else %}
                            No assignment
                        {% endif %}
                    </span>
                {% endfor %}    
            {% else %}
                <p class='info'>No assignment found for the selected subject.</p>
            {% endif %}
            </div>    
        </div>
    </section>

    <section id="topic" class="lightgray">
        <h2>Assignments {% if selected_topics %} for {{ selected_topic.name }} {% else %} by topic {% endif %}</h2>
        <div class="button-list">
        {% if perms.settings.add_topic %}
            <span class="button"><a href="{% url 'settings:new-topic' %}" title="Add your new topic.">+</a></span>
        {% endif %}
        <span class="button"><a href="{% url 'projects:assignment-index' %}#topic">All</a></span>
        {% for topic in topics %}
            <span class="button"><a href="{% url 'projects:assignment-topic' topic.id %}#topic">{{ topic.heading }}</a></span>
        {% endfor %}
        </div>
        
        <div class="wide-envelop">
            <div class="wide-lightgray-block">
            {%if assignments_by_topic and selected_topic %}
                {% for assignment in assignments_by_topic %}
                    <span class="block-envelop">
                        {% if assignment.topic %} 
                            <span class="group">
                                {{ assignment.topic.heading }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:assignment-detail' assignment.id %}">{{ assignment.name }}</a>
                            </span>
                        {% else %}
                            No assignment
                        {% endif %}
                    </span>
                {% endfor %}    
            {%elif assignments_by_topic and not selected_topic %}
                {% for assignment in assignments_by_topic %}
                    <span class="block-envelop">
                        {% if assignment.subject %} 
                            <span class="group">
                                {{ assignment.topic.heading }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:assignment-detail' assignment.id %}">{{ assignment.name }}</a>
                            </span>
                        {% else %}
                            No assignment
                        {% endif %}
                    </span>
                {% endfor %}    
            {% else %}
                <p class='info'>No assignment found for the selected topic.</p>
            {% endif %}
            </div>    
        </div>
    </section>

    {% include "assignment/navigation.html" %}
{% endblock %}

projects/templates/assignment/navigation.html
<section id="navigation">
    <span class="button"><a href="{%  url 'core:dashboard' %}" title="Back to Dashboard.">&lt;</a></span>
    {% if perms.projects.add_submission %}
        <span class="button"><a href="{% url 'projects:assignment-new' %}" title="New Assignment">+</a></span> 
    {% endif %}

    <span class="button"><a href="#top">Last</a></span>
    <span class="button"><a href="#subject">Subject</a></span>
    <span class="button"><a href="#topic">Topic</a></span>
    <form id="logout-form" method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit" class="button-logout">Log Out</button>
    </form>    
</section>

projects/templates/assignment/submission-index.html
{# Assignment template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Submission{% endblock %}

{% block content %}
    <section id="top" class="main">
        <h1>Submissions</h1>
        <div class="wide-white-block">
        {%if submissions %}
            {% for submission in submissions %}
                <span class="block-envelop">
                    {% if submission.assignment %} 
                        <span class="group">
                            {{ submission.assignment.subject.name }}
                            {{ submission.assignment.topic.heading }}
                        </span>
                        <span class="data">
                            <a href="{% url 'projects:submission-detail' submission.id %}">{{ submission.name }}</a>
                        </span>
                    {% else %}
                        No Subject
                    {% endif %}
                </span>
            {% endfor %}    
        {% else %}    
            <p class='info'>No submission found.</p>
        {% endif %}    
        </div>    
    </section>

    <section id="subject" class="darkblue">
        <h2>Assignments {% if selected_subject %} for {{ selected_subject.name }} {% else %} by subject {% endif %}</h2>
        <div class="button-list">
        {% if perms.settings.add_subject %}
            <span class="button"><a href="{% url 'settings:new-subject' %}" title="Add your new subject.">+</a></span>
        {% endif %}
        <span class="button"><a href="{% url 'projects:submission-index' %}#subject">All</a></span>
        {% for subject in subjects %}
            <span class="button"><a href="{% url 'projects:submission-subject' subject.id %}#subject">{{ subject.name }}</a></span>
        {% endfor %}
        </div>
        
        <div class="wide-envelop">
            <div class="wide-darkblue-block">
            {%if submissions_by_subject and selected_subject %}
                {% for submission in submissions_by_subject %}
                    <span class="block-envelop">
                        {% if submission.assignment %} 
                            <span class="group">
                                {{ submission.assignment.subject.name }}
                            {{ submission.assignment.topic.heading }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:submission-detail' submission.id %}">{{ submission.name }}</a>
                            </span>
                        {% else %}
                            No submission
                        {% endif %}
                    </span>
                {% endfor %}    
            {%elif submissions_by_subject and not selected_subject %}
                {% for submission in submissions_by_subject %}
                    <span class="block-envelop">
                        {% if submission.assignment %} 
                            <span class="group">
                                {{ submission.assignment.subject.name }}
                            {{ submission.assignment.topic.heading }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:submission-detail' submission.id %}">{{ submission.name }}</a>
                            </span>
                        {% else %}
                            No submission
                        {% endif %}
                    </span>
                {% endfor %}    
            {% else %}
                <p class='info'>No submission found for the selected subject.</p>
            {% endif %}
            </div>    
        </div>
    </section>

    <section id="topic" class="lightgray">
        <h2>Assignments {% if selected_topics %} for {{ selected_topic.name }} {% else %} by topic {% endif %}</h2>
        <div class="button-list">
        {% if perms.settings.add_topic %}
            <span class="button"><a href="{% url 'settings:new-topic' %}" title="Add your new topic.">+</a></span>
        {% endif %}
        <span class="button"><a href="{% url 'projects:submission-index' %}#topic">All</a></span>
        {% for topic in topics %}
            <span class="button"><a href="{% url 'projects:submission-topic' topic.id %}#topic">{{ topic.heading }}</a></span>
        {% endfor %}
        </div>
        
        <div class="wide-envelop">
            <div class="wide-lightgray-block">
            {%if submissions_by_topic and selected_topic %}
                {% for submission in submissions_by_topic %}
                    <span class="block-envelop">
                        {% if submission.assignment %} 
                            <span class="group">
                                {{ submission.assignment.subject.name }}
                                {{ submission.assignment.topic.heading }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:submission-detail' submission.id %}">{{ submission.name }}</a>
                            </span>
                        {% else %}
                            No submission
                        {% endif %}
                    </span>
                {% endfor %}    
            {%elif submissions_by_topic and not selected_topic %}
                {% for submission in submissions_by_topic %}
                    <span class="block-envelop">
                        {% if submission.assignment %} 
                            <span class="group">
                                {{ submission.assignment.subject.name }}
                                {{ submission.assignment.topic.heading }}
                            </span>
                            <span class="data">
                                <a href="{% url 'projects:submission-detail' submission.id %}">{{ submission.name }}</a>
                            </span>
                        {% else %}
                            No submission
                        {% endif %}
                    </span>
                {% endfor %}    
            {% else %}
                <p class='info'>No submission found for the selected topic.</p>
            {% endif %}
            </div>    
        </div>
    </section>

    {% include "assignment/navigation.html" %}
{% endblock %}