config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("core/", include("core.urls")),
    path("projects/", include("projects.urls")),
    path("settings/", include("settings.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from .views import IndexView
from .views import DashboardView

app_name = 'core'
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
]

settings/urls.py
from django.urls import path

from .views import IndexView
from .views import SubjectView
from .views import TopicView
from .views import SetView

app_name = 'settings'
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("subject/new", SubjectView.as_view(), name="new-subject"),
    path("subject/<int:subject_id>", SubjectView.as_view(), name="subject"),
    path("topic/new", TopicView.as_view(), name="new-topic"),
    path("topic/<int:topic_id>", TopicView.as_view(), name="topic"),
    path("set/new", SetView.as_view(), name="new-set"),
    path("set/<int:set_id>", SetView.as_view(), name="set"),
]

settings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Member(models.Model):

    class Roles(models.TextChoices):
        STUDENT = 'ROLE_STUDENT', _('Student')
        INSTRUCTOR = 'ROLE_INSTRUCTOR', _('Instructor')
        TEACHER = 'ROLE_TEACHER', _('Teacher')
        ADMIN = 'ROLE_ADMIN', _('Admin')
    
    ##Fileds
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.JSONField(choices=Roles.choices, help_text='Select an appropriate role.')
    
    ##Metadata
    
    ##Methods
    def __str__(self):
        return self.user.username


class Subject(models.Model):
    ##Fileds
    name = models.CharField(max_length=100)
    lead = models.ManyToManyField(User)
    #pub_date = models.DateTimeField("date published")

    ##Metadata    
    
    ##Methods
    def get_subjects_by_owner(user):
        return Subject.objects.filter(lead=user.id).order_by('name')

    def __str__(self):
        return self.name


class Topic(models.Model):
    heading = models.CharField(max_length=200)
    text = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    ##Metadata
    
    ##Methods
    def get_topics_by_owner(user):
        return Topic.objects.filter(author=user.id).order_by('heading')

    def __str__(self):
        return self.heading


class Set(models.Model):
    class Types(models.TextChoices):
        YEAR = 'TYPE_YEAR', _('Year Group')
        TUTOR = 'TYPE_TUTOR', _('Tutor Group')
        PERFORM = 'TYPE_PERFORM', _('Performance')
        INTEREST = 'TYPE_INTEREST', _('Interest')

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100, choices=Types)
    lead = models.ManyToManyField(User)
    
    ##Metadata

    ##Methods
    def __str__(self):
        return self.name

settings/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import widgets
from django.contrib.auth.models import User
from django.http import Http404

from .models import Member
from .models import Subject
from .models import Topic
from .models import Set


class SubjectForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        # Filter lead by member roles
        # ROLE_ADMIN: see all teachers and instructors
        member = Member.objects.get(user_id=self.request.user.id)
        if member.Roles.ADMIN in member.role:
            self.fields['lead'].queryset = Member.objects.filter(role__in=[Member.Roles.INSTRUCTOR, Member.Roles.TEACHER])
        else:
            self.fields['lead'].queryset = User.objects.filter(pk=self.request.user.id)
            #NOTE: Left for reference :)
            #self.fields['lead'].queryset = User.objects.filter(pk__in=self.initial.get('lead') or self.data['lead'])
            #self.fields['lead'].widget.attrs['readonly'] = True
        
    class Meta:
        model = Subject
        fields = ['name', 'lead']


class TopicForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        
        # Filter authors by member roles
        # ROLE_ADMIN: see all teachers and instructors
        member = Member.objects.get(user_id=self.request.user.id)
        if member.Roles.ADMIN in member.role or member.Roles.TEACHER in member.role:
            self.fields['author'].queryset = User.objects.filter(member__role__in=[Member.Roles.INSTRUCTOR, Member.Roles.TEACHER])
        else:
            self.fields['author'].queryset = User.objects.filter(pk=self.request.user.id)

    class Meta:
        model = Topic
        fields = ['heading', 'author', 'text']


class SetForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        # Filter lead by member roles
        # ROLE_ADMIN: see all teachers and instructors
        member = Member.objects.get(user_id=self.request.user.id)
        if member.Roles.ADMIN in member.role:
            self.fields['lead'].queryset = User.objects.filter(member__role__in=[Member.Roles.INSTRUCTOR, Member.Roles.TEACHER])
        else:
            self.fields['lead'].queryset = User.objects.filter(pk=self.request.user.id)
        
    class Meta:
        model = Set
        fields = ['type', 'name', 'lead']

settings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.contrib.auth.models import User

from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView

from .models import Member
from .models import Subject
from .models import Topic
from .models import Set

from .forms import SubjectForm
from .forms import TopicForm
from .forms import SetForm


class IndexView(PermissionRequiredMixin, TemplateView):
    """Conbined view for basic settings."""
    
    permission_required = ('settings.view_subject', 'settings.view_topic', 'settings.view_set')
    template_name = "index.html"

    def get(self, request):
        ## Subject and topic section
        if self.get_current_user().member.role == Member.Roles.ADMIN:
            subjects = self.all_subjects()
            topics = self.all_topics()
            sets = self.all_sets()
        else:
            subjects = self.filter_subjects_by_owner()
            topics = self.filter_topics_by_owner()
            sets = self.filter_sets_by_owner()

        ## Render all data
        context = {'subjects':subjects, 'topics':topics, 'sets':sets}
        return render(request, 'settings/index.html', context)
    
    ##Service methods
    def get_current_user(self):
        return User.objects.get(pk=self.request.user.id)

    def all_subjects(self):
        return Subject.objects.all().order_by('name')

    def all_topics(self):
        return Topic.objects.all().order_by('heading')

    def all_sets(self):
        return Set.objects.all().order_by('name')

    def filter_subjects_by_owner(self):
        return Subject.objects.filter(lead=self.request.user.id).order_by('name')

    def filter_topics_by_owner(self):
        return Topic.objects.filter(author=self.request.user.id).order_by('heading')

    def filter_sets_by_owner(self):
        return Set.objects.filter(lead=self.request.user.id).order_by('name')
        

class SubjectView(PermissionRequiredMixin, UpdateView):
    """Creat new or edit existing subject."""
    
    model = Subject
    form_class = SubjectForm
    permission_required = ('settings.change_subject') # If user can change => add
    template_name = "settings/subject.html"
    
    def get(self, request, subject_id=None):
        # Test GET parameters to edit or inser data
        try:
            subject = self.model.objects.get(pk = subject_id)
            form = self.form_class(request=request, initial={'name':subject.name, 'lead':[i.id for i in subject.lead.all()]})
        except self.model.DoesNotExist:
            subject = None
            form = self.form_class(request=request)

        context = {'subject' : subject, 'form' : form}
        return render(request, self.template_name, context)

    def post(self, request, subject_id=None):
        form = self.form_class(request.POST, request=request)
        try:
            # Prepare data to save
            subject = self.model.objects.get(pk = subject_id)

            if form.is_valid():
                subject.name = form.cleaned_data['name']
                subject.lead.set(form.cleaned_data['lead'])
                subject.save()           
        except self.model.DoesNotExist:
            # New Subject form
            if form.is_valid():
                subject = form.save(commit=False)
                subject.save()
                form.save_m2m()

        return HttpResponseRedirect(reverse("settings:index", fragment='#subject'))
        

class TopicView(PermissionRequiredMixin, UpdateView):
    """Creat new or edit existing topic."""
    
    model = Topic
    form_class = TopicForm
    permission_required = ('settings.change_topic')
    template_name='settings/topic.html'
    default_redirect = '/'
    
    def get(self, request, topic_id=None):
        # Test GET parameters to edit or inser data
        try:
            topic = self.model.objects.get(pk = topic_id)
            form = self.form_class(request=request, initial={'heading':topic.heading, 'author':topic.author, 'text':topic.text})
        except self.model.DoesNotExist:
            topic = None
            form = self.form_class(request=request, initial={'author' : request.user.id})

        context = {'topic' : topic, 'form' : form}
        return render(request, self.template_name, context)

    def post(self, request, topic_id=None):
        form = self.form_class(request.POST, request=request)
        try:
            # Prepare data to save
            topic = self.model.objects.get(pk = topic_id)
            
            if form.is_valid():
                topic.heading = form.cleaned_data['heading']
                topic.author = User.objects.get(pk=request.user.id)
                topic.save()
        except self.model.DoesNotExist:
            # New Topic form
            if form.is_valid():
                topic = form.save(commit=False)
                topic.save()
                form.save_m2m()
            
        return HttpResponseRedirect(reverse("settings:index", fragment='#topic'))
        

class SetView(PermissionRequiredMixin, UpdateView):
    """Creat new or edit existing set."""
    
    model = Set
    form_class = SetForm
    permission_required = ('settings.change_set') # If user can change => add
    template_name = "settings/set.html"
    
    def get(self, request, set_id=None):
        # Test GET parameters to edit or inser data
        try:
            set = self.model.objects.get(pk = set_id)
            form = self.form_class(request=request, initial={'name':set.name, 'type':set.type, 'lead':[i.id for i in set.lead.all()]})
        except self.model.DoesNotExist:
            set = None
            form = self.form_class(request=request)

        context = {'set' : set, 'form' : form}
        return render(request, self.template_name, context)

    def post(self, request, set_id=None):
        form = self.form_class(request.POST, request=request)
        try:
            # Prepare data to save
            set = self.model.objects.get(pk = set_id)

            if form.is_valid():
                set.name = form.cleaned_data['name']
                set.type = form.cleaned_data['type']
                set.lead.set(form.cleaned_data['lead'])
                set.save()           
        except self.model.DoesNotExist:
            # New Set form
            if form.is_valid():
                set = form.save(commit=False)
                set.save()
                form.save_m2m()

        return HttpResponseRedirect(reverse("settings:index", fragment='#set'))

settings/templates/settings/index.html
{# Settings template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Settings{% endblock %}

{% block content %}
    <section id="top" class="main">
        <h1>Settings</h1>
        <div class="button-list">
        </div>
    </section>

    <section id="subject" class="darkblue">
        <h2>Subject Management</h2>
        <div class="button-list">
        {% if perms.settings.add_subject %}
            <span class="button"><a href="{% url 'settings:new-subject' %}" title="Add your new subject.">+</a></span>
        {% endif %}
        {%if subjects %}
            {% for subject in subjects %}
                {% if perms.settings.change_subject %}
                    <span class="button"><a href="{% url 'settings:subject' subject.id %}">{{ subject.name }}</a></span>
                {% else %}
                    <span class="button-notactive">{{ subject.name }}</span>
                {% endif %}    
            {% endfor %}
        {% else %}
            <p class='info'>No subjects found. Add some!</p>
        {% endif %}
        </div>
    </section>

    <section id="topic" class="lightgray">
        <h2>Topic Management</h2>
        <div class="button-list">
        {% if perms.settings.add_topic %}
            <span class="button"><a href="{% url 'settings:new-topic' %}" title="Add your new topic.">+</a></span>
        {% endif %}
        {%if topics %}
            {% for topic in topics %}
                {% if perms.settings.change_topic %}
                    <span class="button"><a href="{% url 'settings:topic' topic.id %}">{{ topic.heading }}</a></span>
                {% else %}
                    <span class="button-notactive">{{ topic.heading }}</span>
                {% endif %}    
            {% endfor %}
        {% else %}
            <p class='info'>No topics found. Add some!</p>
        {% endif %}
        </div>
    </section>

    <section id="set" class="darkblue">
        <h2>Set Management</h2>
        <div class="button-list">
        {% if perms.settings.add_set %}
            <span class="button"><a href="{% url 'settings:new-set' %}" title="Add your new set.">+</a></span>
        {% endif %}
        {%if sets %}
            {% for set in sets %}
                {% if perms.settings.change_set %}
                    <span class="button"><a href="{% url 'settings:set' set.id %}">{{ set.name }}</a></span>
                {% else %}
                    <span class="button-notactive">{{ set.name }}</span>
                {% endif %}    
            {% endfor %}
        {% else %}
            <p class='info'>No set found. Add some!</p>
        {% endif %}
        </div>
    </section>

    {% include "settings/navigation.html" %}
{% endblock %}

settings/templates/settings/navigation.html
<section id="navigation">
    <span class="button"><a href="{%  url 'core:dashboard' %}" title="Back to Dashboard.">&lt;</a></span>
    <span class="button"><a href="#top" title="Back to top">^</a></span>
    <span class="button"><a href="#subject">Subjects</a></span>
    <span class="button"><a href="#topic">Topics</a></span>
    <span class="button"><a href="#set">Sets</a></span>
    <form id="logout-form" method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit" class="button-logout">Log Out</button>
    </form>    
</section>

settings/templates/settings/set.html
{# Settings - Set template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Settings - Set{% endblock %}

{% block content %}
    <section id="top" class="form">
        <div class="wide-envelop">
        {%if set %}
            <h1>{{ set.name }}</h1>
            <p>{{set.type}} by {% for lead in set.lead.all %} {{lead.username}} {%if not forloop.last%},{%endif%} {% endfor %}</p>

            <form action="{% url 'settings:set' set.id %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% else %}
            <h1>New set</h1>
            <form action="{% url 'settings:new-set' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% endif %}
        </div>
    </section>

    <section id="navigation">
        <span class="button"><a href="{% url 'settings:index' %}#set" title="Settings">&lt;</a></span>
        <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="button-logout">Log Out</button>
        </form>    
    </section>
{% endblock %}

settings/templates/settings/subject.html
{# Settings - Subjuect template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Settings - Subject{% endblock %}

{% block content %}
    <section id="top" class="form">
        <div class="wide-envelop">
        {%if subject %}
            <h1>{{ subject.name }}</h1>
            <p>by {% for lead in subject.lead.all %} {{lead.username}}{%if not forloop.last%},{%endif%} {% endfor %}</p>

            <form action="{% url 'settings:subject' subject.id %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% else %}
            <h1>New subject</h1>
            <form action="{% url 'settings:new-subject' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% endif %}
        </div>
    </section>

    <section id="navigation">
        <span class="button"><a href="{{ request.session.http_referer }}#subject" title="Settings">&lt;</a></span>
        <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="button-logout">Log Out</button>
        </form>    
    </section>
{% endblock %}

settings/templates/settings/topic.html
{# Settings - Topic template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Settings - Topic{% endblock %}

{% block content %}
    <section id="top" class="form">
        <div class="wide-envelop">
        {%if topic %}
            <h1>{{ topic.heading }}</h1>
            <p>by {{ topic.author }}</p>

            <form action="{% url 'settings:topic' topic.id %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% else %}
            <h1>New topic</h1>
            <form action="{% url 'settings:new-topic' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="wide">    
                    <input type="submit" value="Save">
                </div>
            </form>
        {% endif %}
        </div>
    </section>

    <section id="navigation">
        <span class="button"><a href="{% url 'settings:index' %}#topic" title="Settings">&lt;</a></span>
        <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="button-logout">Log Out</button>
        </form>    
    </section>
{% endblock %}