config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("core/", include("core.urls")),
    path("projects/", include("projects.urls")),
    path("settings/", include("settings.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from .views import IndexView
from .views import DashboardView

app_name = 'core'
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
]

projects/urls.py
from django.urls import path

from . import views
from .views import AssignmentIndexView
from .views import AssignmentNewEditView
from .views import AssignmentDetailView
from .views import AssignmentAddCriteriaView
from .views import CriterionNewEditView
from .views import DescriptorNewEditView
from .views import SubmissionIndexView
from .views import SubmissionDetailView
from .views import SubmissionNewFilesView
from .views import SubmissionNewEditView

app_name = 'projects'
urlpatterns = [
    path("assignment/", AssignmentIndexView.as_view(), name="assignment-index"),
    path("assignment/subject_id=<int:subject_id>", AssignmentIndexView.as_view(), name="assignment-subject"),
    path("assignment/topic_id=<int:topic_id>", AssignmentIndexView.as_view(), name="assignment-topic"),
    path("assignment/new", AssignmentNewEditView.as_view(), name="assignment-new"),
    path("assignment/edit/<int:assignment_id>", AssignmentNewEditView.as_view(), name="assignment-edit"),
    path("assignment/detail/<int:assignment_id>", AssignmentDetailView.as_view(), name="assignment-detail"),
    path("assignment/add/<int:assignment_id>", AssignmentAddCriteriaView.as_view(), name="criteria-add"),
    path("criterion/new", CriterionNewEditView.as_view(), name="criterion-new"),
    path("criterion/edit/<int:criterion_id>", CriterionNewEditView.as_view(), name="criterion-edit"),
    path("descriptor/new", DescriptorNewEditView.as_view(), name="descriptor-new"),
    path("descriptor/edit/<int:descriptor_id>", DescriptorNewEditView.as_view(), name="descriptor-edit"),
    path("submission/", SubmissionIndexView.as_view(), name="submission-index"),
    path("submission/subject_id=<int:subject_id>", SubmissionIndexView.as_view(), name="submission-subject"),
    path("submission/topic_id=<int:topic_id>", SubmissionIndexView.as_view(), name="submission-topic"),
    path("submission/detail/<int:submission_id>", SubmissionDetailView.as_view(), name="submission-detail"),
    path("submission/file", SubmissionNewFilesView.as_view(), name="submission-file"),
    path("submission/new", SubmissionNewEditView.as_view(), name="submission-new"),
    path("submission/edit/<int:submission_id>", SubmissionNewEditView.as_view(), name="submission-edit"),
]

settings/urls.py
from django.urls import path

from .views import IndexView
from .views import SubjectView
from .views import TopicView
from .views import SetView

app_name = 'settings'
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("subject/new", SubjectView.as_view(), name="new-subject"),
    path("subject/<int:subject_id>", SubjectView.as_view(), name="subject"),
    path("topic/new", TopicView.as_view(), name="new-topic"),
    path("topic/<int:topic_id>", TopicView.as_view(), name="topic"),
    path("set/new", SetView.as_view(), name="new-set"),
    path("set/<int:set_id>", SetView.as_view(), name="set"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class File(models.Model):
    '''Represents file in the system.'''
    
    class States(models.TextChoices):
        PUBLIC = 'STATE_PUBLIC', _('Public: everyone can see')
        DRAFT = 'STATE_DRAFT', _('Draft: working on it')
        ARCHIVED = 'STATE_ARCHIVED', _('Archived: stored for me')

    ## Fileds
    name = models.CharField(max_length=255, null=False)
    note = models.CharField(max_length=255, null=True)
    # path = models.TextField(max_length=1024, null=False)
    path = models.FileField(upload_to='storage/', null=True)
    meta = models.JSONField(null=True)
    state = models.JSONField(choices=States.choices)
    version = models.IntegerField(null=False) # To record possible corrections after feedback.
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_created=True)
    updated = models.DateTimeField(auto_now=True)
    
    ## Metadata
    
    ## Methods    
    def filter_by_author(user, limit=None):
        try:
            return File.objects.filter(owner__id=user.id).order_by('-updated')[:limit]
        except File.DoesNotExist:
            return None

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.forms import ModelForm

from core.models import File


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(item, initial) for item in data]
        else:
            result = [single_file_clean(data, initial)]
        return result


class FileForm(ModelForm):
    
    class Meta:
        model = File
        fields = ['name', 'note', 'path', 'state', 'version', 'owner']

core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.template import loader

from django.views.generic import TemplateView
from django.conf import settings

from settings.models import Member


class IndexView(TemplateView):
    """Homepage"""
        
    template_name = "index.html"

    def get(self, request):
        context = {'wolcome':'DIGI Portfolio'}
        return render(request, 'core/index.html', context)


class DashboardView(TemplateView):
    """Homepage for all users after sign in."""
        
    template_name = "index.html"

    def get_current_user(self):
        return Member.objects.get(user_id=self.request.user.id)

    def remove_wizard_steps(self, request):
        ''' Restart wizard steps.'''
        
        if request.session.has_key('wizard'):
            request.session.pop('wizard')

    def get(self, request):
        self.remove_wizard_steps(request=request)
        
        try:
            loged_as = self.get_current_user()
        except Member.DoesNotExist:
            loged_as = None
            #error_msg = "You are not authorised to operate the system. Contact the administrator to grant you access."

        ## Render all data
        context = {'loged_as':loged_as}
        return render(request, 'core/dashboard.html', context)

core/templates/core/dashboard.html
{# Dashboard template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Dashboard{% endblock %}

{% block content %}
    <section id="top" class="main">
        <h1>Dashboard</h1>
        <p>Welcome back {{user.username}}!</p>
    </section>
    <section class="peopleIn">
        <h2>Who is in?</h2>
        {#<span class="button"><a href="{{ path('assignment')}}">Projectss</a></span>#}
    </section> 
    <section class="workload">
        <h2>Workload</h2>
    </section>
    
    {% include "core/navigation.html" %}
{% endblock %}

core/templates/core/index.html
{# Homepage template #}
{% extends 'base.html' %}

{% block title %}DiGi Portfolio | Home{% endblock %}

{% block content %}
    <section id="top" class="main">
        <h1>DiGi Portfolio</h1>
        <p>!</p>
    </section>
    
    <section id="navigation">
        {% if user.is_authenticated %}
            <span class="note" title="It is you.">Logged in as {{ user.username }}.</span>
            <span class="button"><a href="{%  url 'core:dashboard' %}" title="Back to work.">&gt;</a></span>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="button-logout">Log Out</button>
            </form>    
        {% else %}
           <span class="button"><a href="{% url 'login' %}">Log In</a></span>
           {# <span class="button"><a href="{{ path('security_up') }}">Register</a></span> #}
        {% endif %} 
    </section>
{% endblock %}

core/templates/core/navigation.html
<section id="navigation">
    {% if loged_as.user.member.role == 'ROLE_TEACHER' or loged_as.user.member.role == 'ROLE_INSTRUCTOR' or loged_as.user.member.role == 'ROLE_ADMIN' %}
        <span class="button"><a href="{% url 'projects:assignment-index' %}">Assignments</a></span>
        <span class="button"><a href="{% url 'projects:submission-index' %}">Submissions</a></span>
        {# <span class="button"><a href="{% url 'person:index' %}">People</a></span> #}
        <span class="button"><a href="{% url 'settings:index' %}">Settings</a></span>
    {% elif loged_as.user.member.role == 'ROLE_STUDENT' %}
        <span class="button"><a href="{% url 'projects:assignment-index' %}">Assignments</a></span>
        <span class="button"><a href="{% url 'projects:submission-index' %}">Submissions</a></span>
        {# <span class="button"><a href="{% url 'person:profile' current.user.id %}">Profile</a></span> #}
    {% else %}
        <span class="note" title="Please contanct the admin team.">No access to tools.</span>
    {% endif %}
    <form id="logout-form" method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit" class="button-logout">Log Out</button>
    </form>    
    <div class="info">Version 0.1.1 (06/08/25)</div>
</section>